//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KEA.Batchalor.Schedule
{
    using System;
    using System.Collections.Generic;
    
    public partial class userlevel
    {
        public long ID { get; set; }
        public string userlevelname { get; set; }
    }
}
